### ISSUE TITLE
Link to external sites in the menu

### ISSUE THREAD

**Issue by fuzzy76** [nicolas-van/bootstrap-4-github-pages#10]
I've made some code for supporting a 'redirect' variable in page frontmatter to make the menu link to an external site.

See example: https://github.com/fuzzy76/brothersinarms/blob/master/_includes/header.html

Is this something you'd accept a PR on?

**Comment by nicolas-van** [comment]
Hello.

I don't think so. It seems to add useless complexity for something that people can just add themselves in that same file.

Thanks for proposing anyway !
