### ISSUE TITLE
We found potential security vulnerabilities in your dependencies.

### ISSUE THREAD

**Issue by complexgenome** [nicolas-van/bootstrap-4-github-pages#18]
Hi nicolas,

Thanks for this. 
I use boot-strap4 as a template following guidelines on https://nicolas-van.github.io/bootstrap-4-github-pages/

I receive warning on my github for 
`We found potential security vulnerabilities in your dependencies. `

I click on `See dependabot alerts` and get attached message.
![security](https://user-images.githubusercontent.com/5683969/91343215-2df97080-e7aa-11ea-9bfa-a1ddcc605e90.PNG)

How do I remove this?

**Comment by nicolas-van** [comment]
It shouldn't appear anymore.
